spring:
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: drozda-group
      # auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.drozda.sandbox.model
        spring.json.value.default.type: io.drozda.sandbox.model.TradeEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  kafka:
    topics:
      trade-events: trade-events