package io.drozda.sandbox.scenario.consumerfailureandpartitiontakeover.app;
import java.time.Duration; import java.util.*; import java.util.concurrent.*; import org.apache.kafka.clients.consumer.ConsumerRecord; import org.apache.kafka.common.TopicPartition; import io.drozda.sandbox.scenario.consumerfailureandpartitiontakeover.model.TakeoverEvent;
public class TakeoverTracker {
 private final Object monitor=new Object(); private final Map<String,Set<TopicPartition>> assignments=new ConcurrentHashMap<>(); private final List<String> membership=Collections.synchronizedList(new ArrayList<>()); private Set<String> expected=Set.of(); private List<TrackedTakeoverRecord> records=List.of(); private CompletableFuture<List<TrackedTakeoverRecord>> completion=new CompletableFuture<>();
 public CompletableFuture<List<TrackedTakeoverRecord>> expect(List<String> ids){synchronized(monitor){expected=Set.copyOf(ids);records=new ArrayList<>();completion=new CompletableFuture<>();return completion;}}
 public void received(ConsumerRecord<String,TakeoverEvent> record,String consumer){synchronized(monitor){if(!expected.contains(record.value().eventId()))return;records.add(new TrackedTakeoverRecord(record,consumer));if(records.size()==expected.size())completion.complete(List.copyOf(records));}}
 public void assigned(String consumer,Set<TopicPartition> values){assignments.put(consumer,Set.copyOf(values));membership.add(consumer+" assigned "+numbers(values));}
 public void revoked(String consumer,Collection<TopicPartition> values){assignments.put(consumer,Set.of());membership.add(consumer+" revoked "+numbers(values));}
 public Map<Integer,String> awaitOwners(String topic,int ownerCount,Duration timeout){long deadline=System.nanoTime()+timeout.toNanos();while(System.nanoTime()<deadline){Map<Integer,String> owners=owners(topic);if(owners.size()==2&&owners.values().stream().distinct().count()==ownerCount)return Map.copyOf(owners);sleep();}throw new IllegalStateException("Takeover assignment did not stabilize");}
 public List<String> membership(){return List.copyOf(membership);} public void reset(){synchronized(monitor){expected=Set.of();records=List.of();completion=new CompletableFuture<>();assignments.clear();membership.clear();}}
 private Map<Integer,String> owners(String topic){Map<Integer,String> result=new LinkedHashMap<>();assignments.forEach((consumer,values)->values.stream().filter(p->p.topic().equals(topic)).forEach(p->result.put(p.partition(),consumer)));return result;}
 private List<Integer> numbers(Collection<TopicPartition> values){return values.stream().map(TopicPartition::partition).sorted().toList();} private void sleep(){try{Thread.sleep(75);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}}
}
