package io.drozda.sandbox.scenario.consumerfailureandpartitiontakeover.app;
import java.time.Duration; import java.util.*; import java.util.concurrent.TimeUnit; import java.util.stream.IntStream; import io.drozda.sandbox.scenario.consumerfailureandpartitiontakeover.model.TakeoverEvent; import io.drozda.sandbox.scenario.consumerfailureandpartitiontakeover.producer.TakeoverPublisher;
public class TakeoverExperiment {
 private static final int TIMEOUT=20;private final TakeoverPublisher publisher;private final TakeoverTracker tracker;private final TakeoverConsumerControl control;private final String topic;
 public TakeoverExperiment(TakeoverPublisher publisher,TakeoverTracker tracker,TakeoverConsumerControl control,String topic){this.publisher=publisher;this.tracker=tracker;this.control=control;this.topic=topic;}
 public TakeoverScenarioStatus run(String name){Map<Integer,String> initial=Map.of(),after=Map.of();List<TakeoverObservation> observations=new ArrayList<>();String failed=null,survivor=null;int orphan=-1;boolean published=false;try{control.startBoth();initial=tracker.awaitOwners(topic,2,Duration.ofSeconds(TIMEOUT));observations.addAll(publishBatch("BEFORE FAILURE",List.of(0,1),0));published=true;failed=initial.get(1);survivor=initial.get(0);if(failed.equals(survivor)){throw new IllegalStateException("Expected split assignment");}orphan=1;
   TakeoverEvent waiting=new TakeoverEvent(UUID.randomUUID().toString(),"DURING FAILURE",orphan,2,System.currentTimeMillis());var completion=tracker.expect(List.of(waiting.eventId()));control.stop(failed);publisher.publish(topic,waiting).get(TIMEOUT,TimeUnit.SECONDS);after=tracker.awaitOwners(topic,1,Duration.ofSeconds(TIMEOUT));List<TrackedTakeoverRecord> consumed=completion.get(TIMEOUT,TimeUnit.SECONDS);observations.addAll(toObservations(consumed));if(!after.values().stream().allMatch(survivor::equals)||!consumed.get(0).consumer().equals(survivor))throw new IllegalStateException("Survivor did not take over orphaned partition");
   observations.addAll(publishBatch("AFTER TAKEOVER",List.of(0,1),3));return status(name,true,true,failed,survivor,orphan,initial,after,observations,null);
  }catch(Exception e){return status(name,published,false,failed,survivor,orphan,initial,after,observations,root(e));}}
 private List<TakeoverObservation> publishBatch(String phase,List<Integer> partitions,int first)throws Exception{List<TakeoverEvent> events=IntStream.range(0,partitions.size()).mapToObj(i->new TakeoverEvent(UUID.randomUUID().toString(),phase,partitions.get(i),first+i,System.currentTimeMillis())).toList();var future=tracker.expect(events.stream().map(TakeoverEvent::eventId).toList());for(TakeoverEvent e:events)publisher.publish(topic,e).get(TIMEOUT,TimeUnit.SECONDS);return toObservations(future.get(TIMEOUT,TimeUnit.SECONDS));}
 private List<TakeoverObservation> toObservations(List<TrackedTakeoverRecord> values){return values.stream().map(v->new TakeoverObservation(v.record().value().phase(),v.record().value().sequence(),v.record().partition(),v.record().offset(),v.consumer())).toList();}
 private TakeoverScenarioStatus status(String n,boolean p,boolean t,String f,String s,int o,Map<Integer,String> i,Map<Integer,String> a,List<TakeoverObservation> v,String e){return new TakeoverScenarioStatus("consumer-group-consumer-failure",n,true,true,true,p,t,f,s,o,i,a,List.copyOf(v),tracker.membership(),topic,e);}private String root(Exception e){Throwable c=e;while(c.getCause()!=null)c=c.getCause();return c.getMessage()!=null?c.getMessage():c.getClass().getSimpleName();}
}
